[package]
name = "healer_vm"
description = "Healer VM manager"
authors = ["Hao Sun <sunhao.th@gmail.com>"]
version = "0.1.0"
edition = "2018"

[dependencies]
nix = "0.22"
ahash = "0.7"
thiserror = "1.0"
log = "0.4"
healer_io = {path = "../healer_io"}